[package]
name = "pipewire-native-macros"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "*", features = ["extra-traits", "full"] }
quote = "*"
proc-macro2 = "*"

[dev-dependencies]
pipewire-native-spa = { path = "../spa" }

[lib]
proc-macro = true
