[package]
name = "pipewire-native-macros"
version = "0.1.0"
edition = "2024"

[dependencies]
syn = { version = "*", features = ["extra-traits", "full"] }
quote = "*"
proc-macro2 = "*"

[lib]
proc-macro = true
