[package]
name = "pipewire-native-spa"
version = "0.1.0"
edition = "2021"

[dependencies]
pipewire-native-macros = { path = "../macros" }
bitflags = "2.8.0"
libc = "0.2.172"
libloading = "0.8.6"
num = "0.4.3"

[dev-dependencies]
# For tests
libspa = "0.8.0"

[build-dependencies]
cc = "1.2.22"
